[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "RustRCWA"
version = "0.1.0"
edition = "2025"

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
rayon = "1.5"
num = "0.4.0"
tokio = { version = "1.17", features = ["full"] }